import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="flex flex-col w-full items-center supports-[height:100cqh]:h-[100cqh] supports-[height:100svh]:h-[100svh] gap-6 px-4 pt-6 md:px-12">
      <div>{children}</div>
    </main>
  );
}
