import type { Metadata } from 'next';

import { BottomNavBar, TopNavBar } from '@/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PlantsLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="relative flex flex-col w-full items-center supports-[height:100cqh]:h-[100cqh] supports-[height:100svh]:h-[100svh] gap-6 px-4 pt-6 md:px-12">
      <TopNavBar />
      {children}
      <BottomNavBar />
    </main>
  );
}
